dataset_id: "ariG23498/license-detection-paligemma"
model_id: "google/gemma-3-1b-pt"
checkpoint_id: "sergiopaniego/gemma-3-4b-pt-object-detection-aug"

device: "cuda"
dtype: "bfloat16"

batch_size: 16
learning_rate: 2e-5
epochs: 2

finetune_method: "lora"   # FFT | lora | qlora
use_unsloth: false

mm_tunable_parts:
  - multi_modal_projector
  # - vision_tower
  # - language_model