r: 32
alpha: 64
dropout: 0.05
target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - up_proj
  - down_proj
  - gate_proj
max_seq_length: 2048  # Unsloth will RoPE-scale
load_in_4bit: true
load_in_8bit: false